import fs from 'node:fs/promises';
import path from 'node:path';
import { type Theme } from '../../shared/types';
import type { SymbolVariantEntry } from './matrix';

export interface ToolingLogger {
  info: (msg: string) => void;
  warn: (msg: string) => void;
  error?: (msg: string) => never | void;
}

export const GENERATED_BANNER =
  '// This file is auto-generated by @hyrioo/vue-material-symbol\n' +
  '// Do not edit manually.\n';

export async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

export async function ensureDir(dir: string): Promise<void> {
  await fs.mkdir(dir, { recursive: true });
}

export async function writeIfChanged(file: string, content: string): Promise<boolean> {
  let existing = '';
  try {
    existing = await fs.readFile(file, 'utf-8');
  } catch {
    // ignore
  }

  if (existing === content) return false;
  await fs.writeFile(file, content);
  return true;
}

export function defaultLogger(): ToolingLogger {
  return {
    info: (msg: string) => console.info(msg),
    warn: (msg: string) => console.warn(msg),
    error: (msg: string) => {
      throw new Error(msg);
    },
  };
}

export interface ToolingPaths {
  rootDir: string;
  tempDir: string;
  symbolsDir: string;
  distDir: string;
  iconTypesFile: string;
  loaderMapFile: string;
}

export function resolveToolingPaths(rootDir: string): ToolingPaths {
  const tempDir = path.resolve(rootDir, 'node_modules', '@hyrioo', 'vue-material-symbol', '.temp');
  const distDir = path.resolve(rootDir, 'node_modules', '@hyrioo', 'vue-material-symbol', 'dist');
  return {
    rootDir,
    tempDir,
    symbolsDir: path.resolve(tempDir, 'symbols'),
    distDir,
    iconTypesFile: path.resolve(distDir, 'src', 'shared', 'icon-types.d.ts'),
    loaderMapFile: path.resolve(distDir, 'loader-map.js'),
  };
}

export function axesString(weight: number, filled: 0 | 1) {
  const w = weight === 400 ? '' : `wght${weight}`;
  const f = filled === 0 ? '' : `fill${filled}`;
  const s = `${w}${f}`;
  return s.length ? s : 'default';
}

export function buildSymbolUrl(theme: Theme, icon: string, axes: string, size: number) {
  return `https://fonts.gstatic.com/s/i/short-term/release/materialsymbols${theme}/${icon}/${axes}/${size}px.svg`;
}

export function toFilename(icon: string, filled: 0 | 1, weight: number, size: number) {
  const w = Number.isFinite(weight) ? `.w${weight}` : '';
  const s = Number.isFinite(size) ? `.s${size}` : '';
  const fillPart = filled === 1 ? '-fill' : '';
  return `${icon}${fillPart}${w}${s}.svg`;
}

async function removeIfNotSvg(file: string) {
  try {
    const str = await fs.readFile(file, 'utf8');
    const ok = str.startsWith('<svg') && str.includes('</svg>');
    if (!ok) await fs.rm(file, { force: true });
  } catch {
    // ignore
  }
}

export async function withConcurrency<T, R>(
  items: T[],
  limit: number,
  worker: (item: T, i: number) => Promise<R>,
) {
  const ret: R[] = [];
  let idx = 0;

  const run = async () => {
    while (idx < items.length) {
      const i = idx++;
      ret[i] = await worker(items[i], i);
    }
  };

  const runners = Array.from({ length: Math.min(limit, items.length) }, run);
  await Promise.all(runners);
  return ret;
}

export async function downloadSymbols(
  tasks: { url: string; file: string }[],
  concurrency: number,
  options: {
    onProgress?: (progress: { completed: number; total: number; saved: number; failed: number }) => void;
  } = {},
) {
  let failed = 0;
  let skipped = 0;
  let saved = 0;
  const failures: string[] = [];
  const toDownload: { url: string; file: string }[] = [];
  let completed = 0;

  await withConcurrency(tasks, concurrency, async (t) => {
    if (await exists(t.file)) {
      skipped++;
      return;
    }
    toDownload.push(t);
  });

  await withConcurrency(toDownload, concurrency, async (t) => {
    try {
      const res = await fetch(t.url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const svg = await res.text();
      if (!svg.startsWith('<svg')) throw new Error('Not an SVG');

      await fs.writeFile(t.file, svg);
      await removeIfNotSvg(t.file);
      saved++;
    } catch (e) {
      failed++;
      const msg = e instanceof Error ? e.message : String(e);
      failures.push(`[vue-material-symbol] Failed ${t.url} -> ${t.file}: ${msg}`);
    } finally {
      completed++;
      options.onProgress?.({
        completed,
        total: toDownload.length,
        saved,
        failed,
      });
    }
  });

  return { saved, skipped, failed, toDownload: toDownload.length, failures };
}

const ANSI_RESET = '\x1b[0m';
const ANSI_CYAN = '\x1b[36m';
const ANSI_GREEN = '\x1b[32m';

function formatDownloadProgress(completed: number, total: number, color: boolean): string {
  if (!color) {
    return `[vue-material-symbol] Downloading symbols: ${completed}/${total}`;
  }

  return `${ANSI_CYAN}[vue-material-symbol]${ANSI_RESET} Downloading symbols: ${ANSI_GREEN}${completed}/${total}${ANSI_RESET}`;
}

export interface DownloadMatrixOptions {
  concurrency: number;
  logger: ToolingLogger;
}

export async function downloadFromMatrix(
  matrix: SymbolVariantEntry[],
  opts: DownloadMatrixOptions,
): Promise<{ saved: number; skipped: number; failed: number; failures: string[] }> {
  const themeDirs = new Set(matrix.map((row) => path.dirname(row.absoluteFile)));
  for (const dir of themeDirs) {
    await ensureDir(dir);
  }

  const tasks = matrix.map((row) => ({ url: row.url, file: row.absoluteFile }));
  const canInlineProgress = typeof process !== 'undefined' && Boolean(process.stdout?.isTTY);
  let lastLoggedProgress = -1;
  const result = await downloadSymbols(tasks, opts.concurrency, {
    onProgress: ({ completed, total }) => {
      if (total <= 0) return;
      if (completed === lastLoggedProgress) return;
      lastLoggedProgress = completed;
      if (canInlineProgress) {
        process.stdout.write(`\r${formatDownloadProgress(completed, total, true)}`);
      } else {
        opts.logger.info(formatDownloadProgress(completed, total, false));
      }
    },
  });

  if (canInlineProgress && lastLoggedProgress >= 0) {
    process.stdout.write('\n');
  }

  return result;
}
