import fs from 'node:fs/promises';

export interface MetaOptions {
  strict?: boolean;
}

export interface ToolingLogger {
  info: (msg: string) => void;
  warn: (msg: string) => void;
  error?: (msg: string) => never | void;
}

function buildIconTypesContent(union: string): string {
  const banner =
    '// This file is auto-generated by @hyrioo/vue-material-symbol\n' +
    '// Do not edit manually.\n';
  return `${banner}export type MaterialSymbolIcon = ${union};\nexport type IconKey = MaterialSymbolIcon;\n`;
}

async function exists(p: string) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

export async function fetchVersions(
  logger: ToolingLogger,
  versionsFile: string,
  iconTypesFile: string,
  options: MetaOptions,
) {
  if (await exists(versionsFile)) {
    if (await exists(iconTypesFile)) return;

    try {
      const raw = await fs.readFile(versionsFile, 'utf-8');
      const parsed = JSON.parse(raw) as Record<string, unknown>;
      const names = Object.keys(parsed).sort((a, b) => a.localeCompare(b));
      const union = names.length ? names.map((n) => `'${n.replace(/'/g, "\\'")}'`).join(' | ') : 'string';
      await fs.writeFile(iconTypesFile, buildIconTypesContent(union));
      return;
    } catch {
      // Fallback to network fetch path below.
    }
  }

  logger.info('[vue-material-symbol] Fetching Material Symbols metadata...');

  const metaUrl = 'https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true';
  try {
    const res = await fetch(metaUrl);
    if (!res.ok) {
      const msg = `Failed to fetch metadata: HTTP ${res.status}`;
      if (options.strict && logger.error) logger.error(`[vue-material-symbol] ${msg}`);
      else logger.warn(`[vue-material-symbol] ${msg}`);
      return;
    }

    let txt = await res.text();
    if (txt.startsWith(')]}\'')) {
      const i = txt.indexOf('\n');
      if (i !== -1) txt = txt.substring(i + 1);
    }

    let parsed: any;
    try {
      parsed = JSON.parse(txt);
    } catch {
      const msg = 'Failed to parse metadata JSON';
      if (options.strict && logger.error) logger.error(`[vue-material-symbol] ${msg}`);
      else logger.warn(`[vue-material-symbol] ${msg}`);
      return;
    }

    if (!parsed || !Array.isArray(parsed.icons)) {
      await fs.writeFile(versionsFile, txt);
      return;
    }

    const versions: Record<string, string | number> = {};
    for (const icon of parsed.icons) {
      const families = Array.isArray((icon as any)?.unsupported_families)
        ? ((icon as any).unsupported_families as any[])
        : [];

      if (families.some((fam) => String(fam).toLowerCase().includes('symbols'))) continue;

      const name = String((icon as any)?.name || '');
      if (!name) continue;
      versions[name] = (icon as any)?.version;
    }

    const sorted = Object.fromEntries(Object.entries(versions).sort((a, b) => a[0].localeCompare(b[0])));
    await fs.writeFile(versionsFile, JSON.stringify(sorted, null, 2));

    const names = Object.keys(sorted);
    const union = names.length ? names.map((n) => `'${n.replace(/'/g, "\\'")}'`).join(' | ') : 'string';
    const content = buildIconTypesContent(union);

    let existing = '';
    try {
      existing = await fs.readFile(iconTypesFile, 'utf-8');
    } catch {
      // ignore
    }

    if (existing !== content) {
      await fs.writeFile(iconTypesFile, content);
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    if (options.strict && logger.error) logger.error(`[vue-material-symbol] Metadata prefetch failed: ${msg}`);
    else logger.warn(`[vue-material-symbol] Metadata prefetch failed: ${msg}`);
  }
}
