import fs from 'node:fs/promises';
import { toFilename } from './symbols';
import {
  type DefineCustomMap,
  type DefineCustomSource,
  type DefinedIcons,
  type Filled,
  type IconConfig,
  type OpticalSize,
  type SvgFileSource,
  type SymbolKey,
  type SymbolSvg,
  type Theme,
  type Weight,
} from '../shared/types';
import { customKeyOf, keyOf, normalizeFills, normalizeNums, normalizeThemes, unique } from '../shared/utils';
import type { MaterialSymbolIcon } from '../shared/icon-types';

export type {
  OpticalSize,
  Weight,
  Filled,
  Theme,
  SymbolKey,
  SymbolSvg,
  IconConfig,
  DefinedIcons,
  DefineCustomMap,
  DefineCustomSource,
  SvgFileSource,
};

export function defineIcons<
  S extends Partial<Record<MaterialSymbolIcon, Partial<IconConfig>>>,
  C extends DefineCustomMap = {},
  D extends Partial<IconConfig> = {}
>(symbols: S, custom: C, defaults: D): DefinedIcons {
  return {
    Symbols: symbols as any,
    Custom: custom ?? ({} as C),
    Default: defaults ?? ({} as D),
  } as const;
}

export const IconDefaultConfig = {
  sizes: [20, 24, 40, 48] as const,
  weights: [400] as const,
  fills: [0] as const,
  themes: ['rounded'] as const,
};

const SYMBOLS_ROOT_PATH = '/node_modules/@hyrioo/vue-material-symbol/.temp/symbols';

export function svg(filePath: string): SvgFileSource {
  return { __hyriooSvgFile: filePath };
}

function toJsStringLiteral(value: string): string {
  // Keep generated JS safe for import-analysis, including uncommon Unicode line separators.
  return JSON.stringify(value)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function isSvgFileSource(value: unknown): value is SvgFileSource {
  return Boolean(value && typeof value === 'object' && '__hyriooSvgFile' in value);
}

export async function generateConsumerFiles(
  logger: { warn: (msg: string) => void },
  iconsDef: DefinedIcons,
  iconTypesFile: string,
  loaderMapFile: string,
  distDir: string,
  options: { writeLoaderMap?: boolean } = {},
) {
  const writeLoaderMap = options.writeLoaderMap ?? true;
  const banner =
    '// This file is auto-generated by @hyrioo/vue-material-symbol\n' +
    '// Do not edit manually.\n';
  let loaderMapContent = 'const RAW_MAP = {};\nexport default RAW_MAP;\n';

  try {
    // logger.warn('[vue-material-symbol] Generate icon-types.d.ts');
    const symKeys = Object.keys(iconsDef.Symbols || {});
    const customKeys = Object.keys(iconsDef.Custom || {});
    const all = Array.from(new Set([...symKeys, ...customKeys]));
    const keyUnion = all.length ? all.map((n) => `'${n.replace(/'/g, "\\'")}'`).join(' | ') : 'string';
    let materialIconType = 'string';
    try {
      const existingTypes = await fs.readFile(iconTypesFile, 'utf-8');
      const match = existingTypes.match(/export type MaterialSymbolIcon = ([^;]+);/);
      if (match?.[1]) {
        materialIconType = match[1];
      }
    } catch {
      // ignore
    }

    const typeContent =
      `${banner}` +
      `export type MaterialSymbolIcon = ${materialIconType};\n` +
      `export type IconKey = ${keyUnion};\n`;

    await fs.mkdir(distDir, { recursive: true });

    let existing = '';
    try {
      existing = await fs.readFile(iconTypesFile, 'utf-8');
    } catch {
      // ignore
    }

    if (existing !== typeContent) {
      await fs.writeFile(iconTypesFile, typeContent);
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    logger.warn(`[vue-material-symbol] Failed to write icon-types.d.ts: ${msg}`);
  }

  try {
    // logger.warn('[vue-material-symbol] Generate loader-map.js');
    const imports: string[] = [];
    const mapEntries: string[] = [];
    const defaults: Partial<IconConfig> = iconsDef.Default ?? {};

    let i = 0;
    for (const [icon, meta] of Object.entries(iconsDef.Symbols || {})) {
      const sizes = normalizeNums(meta.sizes ?? defaults.sizes, IconDefaultConfig.sizes);
      const weights = normalizeNums(meta.weights ?? defaults.weights, IconDefaultConfig.weights);
      const fills = normalizeFills(meta.fills ?? defaults.fills, IconDefaultConfig.fills);
      const themes = normalizeThemes(meta.themes ?? defaults.themes, IconDefaultConfig.themes);

      for (const theme of unique(themes)) {
        for (const weight of unique(weights)) {
          for (const filled of unique(fills)) {
            const key = keyOf({ theme, icon, filled, weight } as any);
            const entries: string[] = [];

            for (const size of unique(sizes)) {
              const filename = toFilename(icon, filled as 0 | 1, weight, size);
              const importPath = `${SYMBOLS_ROOT_PATH}/${theme}/${filename}?raw`;
              const varName = `i${i++}`;
              imports.push(`import ${varName} from '${importPath}';`);
              entries.push(`      ${size}: ${varName}`);
            }

            mapEntries.push(`  '${key}': {\n${entries.join(',\n')}\n  },`);
          }
        }
      }
    }

    for (const [icon, sizesObj] of Object.entries(iconsDef.Custom || {})) {
      const key = customKeyOf({ icon } as any);
      const entries: string[] = [];

      for (const [sizeKey, val] of Object.entries((sizesObj as any) || {})) {
        let value = val;
        if (value && typeof value === 'object' && 'then' in value && typeof (value as any).then === 'function') {
          value = await value;
        }

        if (isSvgFileSource(value)) {
          const varName = `i${i++}`;
          imports.push(`import ${varName} from '${value.__hyriooSvgFile}?raw';`);
          entries.push(`      ${sizeKey}: ${varName}`);
        } else if (typeof value === 'string' && (value.startsWith('./') || value.startsWith('../'))) {
          const varName = `i${i++}`;
          imports.push(`import ${varName} from '${value}?raw';`);
          entries.push(`      ${sizeKey}: ${varName}`);
        } else if (value) {
          const content = typeof value === 'object' && 'default' in value ? (value as any).default : value;
          if (typeof content === 'string') {
            entries.push(`      ${sizeKey}: ${toJsStringLiteral(content)}`);
          }
        }
      }

      if (entries.length) {
        mapEntries.push(`  '${key}': {\n${entries.join(',\n')}\n  },`);
      }
    }

    const mapContent = `${banner}${imports.join('\n')}\n\nexport default {\n${mapEntries.join('\n')}\n};\n`;
    loaderMapContent = mapContent;

    if (writeLoaderMap) {
      let existing = '';
      try {
        existing = await fs.readFile(loaderMapFile, 'utf-8');
      } catch {
        // ignore
      }

      if (existing !== mapContent) {
        await fs.writeFile(loaderMapFile, mapContent);
      }
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    logger.warn(`[vue-material-symbol] Failed to write loader-map.js: ${msg}`);
  }

  return {
    loaderMapContent,
  };
}
